### ISSUE TITLE
Project Overview - Final Review

### ISSUE THREAD

**Issue by mcamarco** [dannydelts94/the-19th-hole#1]
- [x] Project Title - Team Collaborated
- [x] Project Description - @mcamarco 
- [x] User Story - @PaulJay22 
- [x] WireFrame or Sketch of design - @DScoderman 
- [x] User Flow Diagram - @mcamarco 
- [x] API's to be used - @PaulJay22 @mcamarco @DScoderman @dannydelts94 
- [x] Rough breakdown of tasks and link to dashboard - Tasks: @mcamarco 
- [x] REPO & Project Created - @dannydelts94

**Comment by DScoderman** [comment]
added sketch images in slack channel. Link to wireframe is here: 

[19th hole wireframe.pdf](https://github.com/dannydelts94/Drinkin-N-Drivin/files/11140523/19th.hole.wireframe.pdf)

**Comment by mcamarco** [comment]
Team Invite link for User Flow Diagram [](https://miro.com/welcomeonboard/alB2M3pXT1dQdXBSdFA5ZG8zZU8yNGZKMlA0T1ZYcEdQQ214U3Bnc2VPcEt2RmsyQTVKVExVR09lRkVZZDhRbXwzNDU4NzY0NTUwNzAwNTAxMjYxfDI=?share_link_id=302815959126)
